spring:
  cloud:
    gateway:
      routes:
      - id: unibbs-security
        uri: lb://unibbs-security
        # uri: http://localhost:9010
        predicates:
        - Path=/security/**,/login/**
      - id: profile-route
        uri: lb://unibbs-profile
        predicates:
        - Path=/profile/**
      - id: forum-route
        uri: lb://unibbs-forum
        predicates:
        - Path=/post/**,/community/**
      
