# yaml 配置
version: '3'
services:
  web:
    build: .
    ports:
      - "9010:9010"
    depends_on:
      - redis
      - mysql
      - nacos
      - seata
  redis:
    image: "redis"
  mysql:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  nacos:
    image: nacos/nacos-server
  seata:
    image: seataio/seata-server